DROP DATABASE IF EXISTS cookhub;

CREATE DATABASE cookhub
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE cookhub;

SELECT SCHEMA_NAME, DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME
FROM INFORMATION_SCHEMA.SCHEMATA
WHERE SCHEMA_NAME = 'cookhub';
